name: laska
description: A simple command-line application.
version: 0.1.0-wip
homepage: https://tenderowl.com/work/laska

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  mime: ^2.0.0
  mime_type: ^1.0.0
  event: ^3.0.0
  ioc_container: ^1.0.12
#  path: ^1.7.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
